### ISSUE TITLE
Need Java Script code

### ISSUE THREAD

**Issue by bhaveshv007** [hamidsn/deferred-deeplink#1]
Hello @hamidsn ,

I like your developed concept.

I want to java script.

Can you please enable the below Urls?

view-source:https://www.iranatlas.info/droid/deferred-deeplink.htm

You can test its functionality by bewlow sample URLs:

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=yellow

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=black

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=blue

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=orange

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=red

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=green

Thanks in Advance

**Comment by hamidsn** [comment]
Hello,
Links are up, you can view their source code.App is removed from play.
ThanksHamid

Sent from Yahoo Mail on Android 
 
  On Wed, 31 Mar 2021 at 9:04 pm, ***@***.***> wrote:   


Hello @hamidsn ,

I like your developed concept.

I want to java script.

Can you please enable the below Urls?

view-source:https://www.iranatlas.info/droid/deferred-deeplink.htm

You can test its functionality by bewlow sample URLs:

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=yellow

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=black

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=blue

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=orange

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=red

https://www.iranatlas.info/droid/deferred-deeplink.htm?color=green

Thanks in Advance

**Comment by bhaveshv007** [comment]
Thank you for your quick response.
